name: Create the Windows wheels based on >= python3.13

on:
  push:
    branches: ["py313wheel"] # Assign the branch that triggers this workflow

jobs:
  build-windows-wheel:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          architecture: "x64"

      - name: Install MSYS2 + gfortran
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc-fortran

      - name: Add MSYS2 to PATH
        run: |
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Install dependencies and cibuildwheel # Upgrade to >=3.1.0 after Python3.14 final release
        shell: bash
        run: |
          python -m pip install cibuildwheel==3.1.0 delvewheel
         

      - name: Build wheels
        shell: bash
        run: cibuildwheel --platform windows --output-dir wheelhouse
        env:
          CIBW_ARCHS: "AMD64"
          FC: gfortran
          CC: gcc
          CXX: g++
          CIBW_BUILD: "cp314-*"
          CIBW_TEST_REQUIRES: "numpy"
          CIBW_TEST_COMMAND: "python -c \"import apexpy; print(apexpy.__version__)\" && python {project}/tests/example.py"

          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:\\\\msys64\\\\mingw64\\\\bin -w {dest_dir} {wheel}"

      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels
          path: wheelhouse/*.whl
